// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nebfdvwjccvoknzmrach.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYmZkdndqY2N2b2tuem1yYWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDQ1NTksImV4cCI6MjA2MjkyMDU1OX0.FxbM3Do0dGBj4FJMol7L8vZudrIxycWnHyfIv9wupVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);